stages:
  - "1"
  - "2"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

latex:
  stage: "1"
  before_script:
    - sh ci/latex/before_script.sh
  script:
    - sh ci/latex/script.sh
  artifacts:
    paths:
      - LaTeX/notes.pdf
    expire_in: 6 months

python:
  stage: "1"
  before_script:
    - sh ci/python/before_script.sh
  script:
    - sh ci/python/script.sh
  artifacts:
    paths:
      - python/output/
    expire_in: 6 months

package:
  stage: "2"
  before_script:
    - sh ci/package/before_script.sh
  script:
    - sh ci/package/script.sh
  artifacts:
    paths:
      - sandpile.tar.xz
    expire_in: 6 months
